"""update database schema

Revision ID: 23da46723d9b
Revises: b66f9a017a3a
Create Date: 2025-05-14 15:47:26.287680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23da46723d9b'
down_revision = 'b66f9a017a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.String(), default='pending'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
