"""empty message

Revision ID: b66f9a017a3a
Revises: 71c85872c4e0
Create Date: 2025-05-13 19:49:01.209191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66f9a017a3a'
down_revision = '71c85872c4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
